# Generated by Django 5.2.7 on 2025-10-30 23:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('data_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaUniversidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qtde_professores', models.IntegerField()),
                ('qtde_disciplinas', models.IntegerField()),
                ('qtde_avaliacoes', models.IntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('admin', 'Admin')], max_length=10)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplinaPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.disciplina')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('disciplina', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('disciplina_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.disciplinapessoa')),
            ],
        ),
        migrations.CreateModel(
            name='MediaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qtde_avaliacoes', models.IntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('disciplina_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.disciplinapessoa')),
            ],
        ),
        migrations.CreateModel(
            name='MediaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qtde_disciplinas', models.IntegerField()),
                ('qtde_avaliacoes', models.IntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.avaliacao')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.categoria')),
            ],
            options={
                'unique_together': {('avaliacao', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='MediaDisciplinaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qtde_avaliacoes', models.IntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.categoria')),
                ('disciplina_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.disciplinapessoa')),
            ],
            options={
                'unique_together': {('disciplina_pessoa', 'categoria')},
            },
        ),
    ]
