# Generated by Django 5.2.7 on 2025-10-08 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('data_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaUniversidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qtde_professores', models.IntegerField()),
                ('qtde_disciplinas', models.IntegerField()),
                ('qtde_avaliacoes', models.IntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('admin', 'Admin')], max_length=10)),
                ('admin', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.disciplina')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.pessoa')),
            ],
            options={
                'unique_together': {('disciplina', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('disciplina_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.disciplinapessoa')),
            ],
        ),
        migrations.CreateModel(
            name='MediaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qtde_avaliacoes', models.IntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('disciplina_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.disciplinapessoa')),
            ],
        ),
        migrations.CreateModel(
            name='MediaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qtde_disciplinas', models.IntegerField()),
                ('qtde_avaliacoes', models.IntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.avaliacao')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.categoria')),
            ],
            options={
                'unique_together': {('avaliacao', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='MediaDisciplinaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qtde_avaliacoes', models.IntegerField()),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.categoria')),
                ('disciplina_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_avaliation.disciplinapessoa')),
            ],
            options={
                'unique_together': {('disciplina_pessoa', 'categoria')},
            },
        ),
    ]
